export { default as Heading } from "./Heading"
export { default as Paragraph } from "./Paragraph"
export { default as Button } from "./Button"
export { default as Switch } from "./Switch"
export { default as Image } from "./Image"
